# Generated by Django 2.2.2 on 2019-10-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_baset_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baset',
            name='source',
        ),
    ]
