# Generated by Django 2.2.2 on 2019-10-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_baset_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menshawy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(default='محمد صديق المنشاوي', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
    ]
