# Generated by Django 2.2.2 on 2019-10-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_menshawy_radio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Husary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(default='محمود خليل الحصري', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
    ]
